#!/bin/bash
if [ $# -eq 0 ]
then
set $1 "help"
fi
if [[ "$1" == "twopacoclean" ]]
then
shift
grep -v ^C $@
elif [[ "$1" == "help" ]]
then
/usr/local/bin/k8 /usr/local/bin/gfatools.js
echo "Local commands:"
echo "          twopacoclean  Remove Containment from TwoPaCo GFA"
else
/usr/local/bin/k8 /usr/local/bin/gfatools.js $@
fi
