#!/bin/sh
if [ $# -eq 2 ]
then
vg view -d $1 | sfdp -Tsvg | perl -pne 's/id="node\d*"(.*<title>)(\d*)/id="$2"$1$2/;s/id="edge\d*"(.*<title>)(\d*):ne..45..gt.(\d*)/id="$2-$3" data-from="$2" data-to="$3"$1$2:ne&#45;&gt;$3/;' > $2
else
vg view -d $1 | sfdp -Tsvg | perl -pne 's/id="node\d*"(.*<title>)(\d*)/id="$2"$1$2/;s/id="edge\d*"(.*<title>)(\d*):ne..45..gt.(\d*)/id="$2-$3" data-from="$2" data-to="$3"$1$2:ne&#45;&gt;$3/;'
fi
